### ISSUE TITLE
[BUG] can not run with msg(runtime error : invalid memory ...)

### ISSUE THREAD

**Issue by greyHairChooseLife** [dlvhdr/gh-dash#257]
**Describe the bug**

I just installed with `gh extension installed .. ` as provided on README and run it. But it seems like it did not run successfully. I just got an error messages as stderr.

There are 2 clues I guess. 

1. It returns a bit better output when I try `gh dash > returning`. I left output below.
2. It works fine with xterm, instead of rxvt. But it says <Auth token not found for host github.com> when I reload with `r` or `R`.

Here is what it return as error message. First for stderr, second for the output as running with `gh dash > returning`.

Here is FIRST,
```
^[]11;rgba:0000/0000/0000/e666^[^[[32;1R^[]10;rgb:adad/d8d8/e6e6^[^[[32;41RCaught panic:

runtime error: invalid memory address or nil pointer dereference

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/Cellar/go/1.20.3/libexec/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/Cellar/go/1.20.3/libexec/src/runtime/debug/stack.go:16 +0x19
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
	/Users/dolevh/code/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.0/tea.go:385 +0x95
panic({0xd017c0, 0x15573a0})
	/usr/local/Cellar/go/1.20.3/libexec/src/runtime/panic.go:884 +0x213
github.com/dlvhdr/gh-dash/ui/components/issuessection.FetchAllSections({{0x0, 0x0}, 0x2e, 0xae, 0xae, 0x29, 0x0, {0x0, 0x0}, {0x0, ...}, ...})
	/Users/dolevh/code/personal/gh-dash/ui/components/issuessection/issuessection.go:275 +0x92
github.com/dlvhdr/gh-dash/ui.(*Model).fetchAllViewSections(0xc000270350?)
	/Users/dolevh/code/personal/gh-dash/ui/ui.go:497 +0xf9
github.com/dlvhdr/gh-dash/ui.Model.Update({{{0x0, 0x0}, {{0xc000236a60, 0x2, 0x2}, {{...}, {...}}, 0x0}, {{0xc000236aa0, 0x2, ...}, ...}, ...}, ...}, ...)
	/Users/dolevh/code/personal/gh-dash/ui/ui.go:184 +0x2f4f
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc00013a0b0, {0xfff440?, 0xc0000ee000?}, 0xffc160?)
	/Users/dolevh/code/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.0/tea.go:324 +0x60a
github.com/charmbracelet/bubbletea.(*Program).Run(0xc00013a0b0)
	/Users/dolevh/code/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.0/tea.go:448 +0x91a
github.com/dlvhdr/gh-dash/cmd.init.0.func1(0x1562200?, {0xda4331?, 0x0?, 0x0?})
	/Users/dolevh/code/personal/gh-dash/cmd/root.go:131 +0x255
github.com/spf13/cobra.(*Command).execute(0x1562200, {0xc000022240, 0x0, 0x0})
	/Users/dolevh/code/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1562200)
	/Users/dolevh/code/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/dolevh/code/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/dlvhdr/gh-dash/cmd.Execute()
	/Users/dolevh/code/personal/gh-dash/cmd/root.go:41 +0x25
main.main()
	/Users/dolevh/code/personal/gh-dash/gh-dash.go:8 +0x17
```

And SECOND,
```
[?25l[?1049h[2J[1;1H[1;1H[?25l                                                                            
  [2m[0m  |  [1;;mMy Pull Requests[0m  |  [2mNeeds My Review[0m  |  [2mInvolved[0m  [1;;m[ PRs][0m[;m[ Issues][0m
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ╭──────────────────────────╮                                                          │               Nothing selected...               
 │ is:pr [2m[0m[2mi[0m[2ms:open author:@me[0m│                                                                                                            
 ╰──────────────────────────╯                                                                                                            
 [1m Tip:[0m you can change the search query by pressing  [;m/[0m  and submitting it with  [;mEnter[0m                                                    
────────────────────────────────────────────────────
 authentication token not found for host github.com[9;0H[2K[1A[2K[1A[1A[1A[1A[1A[1A[1A[0D[2K                                                                            
[1B[1B[1B[1B[1B[1B──────────────────────
? toggle help • q quit[9;0H[2K[?25h[?1002l[?1003l[?1049l[?25hCaught panic:

runtime error: slice bounds out of range [2:1]

Restoring terminal...
```

**To Reproduce**
1. install with `gh extension install ...`
4. run `gh dash`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: manjaro linux
 - TERM: rxvt-256
 - Just in case, recently, I am in trouble about input method with rxvt. I use the ibus, ibus-hangle for input method to swap between English and Korean.  When I toggle from one to another, it gets like 30% chance to stop working with Korean. I couldnt even reproduce it with my intendtion. IMO, it could have caused this issue to me.

**Comment by dlvhdr** [comment]
Please update your `gh` cli as well as `gh-dash` to their latest versions as this was just fixed a couple of days ago.
